name: Workflow reutilizável Deploy na aws teste

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
    secrets:
        ACCESS_KEY: 
            required: true
        SECRET_KEY:
            required: true

jobs:
  deploy-lambda:
    name: Deploy da lambda
    runs-on: ${{inputs.runs-on}}
    steps:
        - name: Python Config
          uses: actions/setup-python@v3
          with:
            python-version: 3.8
        - name: Copy
          run: cp -R . /lambda
        - name: Install dependencies
          run: pip install --target ./lambda -r ./app/requirements.txt --upgrade --no-user
        - name: Zip files
          run: zip -j lambda_deploy.zip ./lambda/*

        
        
         
