name: Workflow reutilizável Deploy na aws teste

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      function-name:
        required: true
        type: string
    secrets:
        ACCESS_KEY: 
            required: true
        SECRET_KEY:
            required: true

jobs:
  deploy-lambda:
    name: Deploy da lambda
    runs-on: ${{inputs.runs-on}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      
      - uses: sigstore/gh-action-sigstore-python@v1.2.3
      
      - name: Install dependencies
        run: pip install --target . -r ./app/requirements.txt --upgrade --no-user   

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Zip Lambda function
        run: zip -r lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b8c74de
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{inputs.function-name}} \
            --zip-file fileb://lambda.zip

        
        
         
